"""Added new field

Revision ID: 5f34a9f7fb24
Revises: a3b7ad74be2c
Create Date: 2023-01-31 14:27:26.128575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f34a9f7fb24'
down_revision = 'a3b7ad74be2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
